library(dplyr)
MechaCar = read.csv("MechaCar_mpg.csv")
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = MechaCar)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = MechaCar))
SusCoil = read.csv("Suspension_coil.csv")
Total_summary <- SusCoil %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI), .groups = 'keep' )
Lot_summary <- SusCoil %>% group_by(Manufacturing_Lot) %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI), .groups = 'keep' )
t.test(SusCoil$PSI, mu = 1500)
lot1 <- subset(SusCoil, Manufacturing_Lot == "Lot1")
lot2 <- subset(SusCoil, Manufacturing_Lot == "Lot2")
lot3 <- subset(SusCoil, Manufacturing_Lot == "Lot3")
t.test(lot1$PSI, mu = 1500)
t.test(lot2$PSI, mu = 1500)
t.test(lot3$PSI, mu = 1500)
